server:
  port: 30001

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(+GawgltfrJwbnZajyrU7w8ywRHrdnDvVrLF7cT6hzhf5Kr9J7uiqrsuIlL4fcNh5AMJA7jCXTX7PLfKjhDCBjVmxH6l5hyxHhR/4/mHC+RYYQEdczVdm1NIbQqAqMcKC)
    username: ENC(JUkLZ6DAw5w6m32WfcdGJw==)
    password: ENC(1a+qXHGSQc7voRLmz3sQpU2rUHS1eJYy)
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

token:
  expiration_time: 86400000
  secret: ENC(DRze1Pg8l/Uabcg/Gv3JmRyg8KkW5NhT0XRdEHnfcjkYQrEXuCcCZo5+nWqQ7Tin)


gateway:
  ip: 192.168.0.5