server:
  port: 30001

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(2B/sDqP0AN35i5ns3lapRedrPMjRWKkRskHWX50En48nYDvpfsdRQy7x11ZdRDkN5AJ7RCXuSp2kyUKOiubUJ7alx9qdNhfsivfoIhLJM8IxUjttbizFgzqAy6oOuSBUQUijuoOKaQ0=)
    username: ENC(JUkLZ6DAw5w6m32WfcdGJw==)
    password: ENC(1a+qXHGSQc7voRLmz3sQpU2rUHS1eJYy)
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

token:
  expiration_time: ENC(rMHWZsK9obmgTK6vt1JGP8f+mcv38uCK)
  secret: ENC(DRze1Pg8l/Uabcg/Gv3JmRyg8KkW5NhT0XRdEHnfcjkYQrEXuCcCZo5+nWqQ7Tin)


gateway:
  ip: ENC(bU7cB4kA4WqZvHRTLkPjtjKLvUGF5uPn)