server:
  port: 30002

spring:
  application:
    name: menu-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(DbwRyq36dZgZCURnQ2uL1INyyvTonuq53jwotKNQvwkCsP1Zy5orv1dBenPoF089fjdlWlG97iMT4Y5V6qvD093diK7DaOcpDm5nxCbKBIOI+Rc5SV6OsPMjdIs8bQv0JI4x76/xbCg=)
    username: ENC(Nd+Vj8M4nZo2t0n/DS3jnQ==)
    password: ENC(BoioX8FZlGJfT+erSyzHK14m7FkKJqEO)
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

