server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      # 테스트 간에 cors 모두 허용
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
        add-to-simple-url-handler-mapping: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
            - Method=POST
          filters:
            # 원 주소 -> 바뀔 주소. 패스를 다시 지정한다.
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
            - Method=GET,PUT,DELETE
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: menu-service
          uri: lb://MENU-SERVICE
          predicates:
            - Path=/menu-service/**
          filters:
            - RewritePath=/menu-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


token:
  secret: ENC(JLW/vJDxl4GiIIhPVmRVqR7r2ckFS9xibV7g5QNbqzlo4XKw0U4jp2uQlboXiztK)
